### ISSUE TITLE
Краш программы при отсутствие файла базы данных

### ISSUE THREAD

**Issue by AdaaMark** [MyTh1c2L/TechnicalSupport#5]
Если по каким-то причинам файл базы данных стал недоступен (был переименован, перемещен, удален и т.п.), то программа просто не запускается, или крашится.

**Comment by MyTh1c2L** [comment]
При запуске программы добавлено условие, проверяющее существование файла базы данных по указанному пути. При отсутствие данного файла, программа предложит загрузить новый файл с БД
