### ISSUE TITLE
Краш программы при открытии новой базы данных 

### ISSUE THREAD

**Issue by AdaaMark** [MyTh1c2L/TechnicalSupport#6]
Если открывать окно с выбором загрузки в программу нового файла с базой данных, то возможен краш программы, если файл не был выбран, а окно было закрыто

**Comment by MyTh1c2L** [comment]
Добавлено условие, проверяющие, что переменная, хранящая путь к файлу, содержит эту информацию, а не является пустой.
Проблема решена
