### ISSUE TITLE
Возможность ввода текста в поля вывода информации

### ISSUE THREAD

**Issue by Homo-erectus** [MyTh1c2L/TechnicalSupport#9]
На формах используются элементы вывода информации для пользователя, и в эти элементы пользователь может вводить информацию.

**Comment by MyTh1c2L** [comment]
В тех местах, где возможно пригодиться копирование текста оставлены TextBox с параметром ReadOnly. На формах проблем и тарифов вместо TextBox отныне используется label
Проблема решена
